name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: pre-commit/action@v3.0.0

    - name: Install dependencies
      run: pip install pytest .

    - name: Run pytest
      run: pytest
